#This function takes a matrix and stores it and its inverse (when calculate by cacheSolve(), otherwise stores NULL)
#Example of x: matrix(sample(c(0,1,2,3,4,5,6,7,8,9), 4), 2, 2)
makeCacheMatrix <- function(x = matrix()) {
  inverseMatrix <- NULL
  #Function just set the value, no return
  set <- function(newMatrix){
    x <<- newMatrix
    inverseMatrix <<- NULL
  }
  get <- function(){
    return (x)
  }
  #Function just set the value, no return
  setInverseMatrix <- function(newValueInverseMatrix){
    inverseMatrix <<- newValueInverseMatrix
  }
  getInverseMatrix <- function(){
    return (inverseMatrix)
  }
  return (list(set = set, get = get, setInverseMatrix = setInverseMatrix, getInverseMatrix = getInverseMatrix))
}

#Calculates the inverse of a "special matrix" (those generated by the top function)
cacheSolve <- function(x, ...) {
  library(MASS) #Solve the inverse of a matrix NxM
  inverseMatrix <- x$getInverseMatrix()
  if(!is.null(inverseMatrix)){
    message("getting cached data")
    return(inverseMatrix)
  }
  matrixData <- x$get()
  inverseMatrix <- ginv(matrixData) #calculate the inverse of a matrix unsig the function ginv (from library MASS)
  x$setInverseMatrix(inverseMatrix)
  return (inverseMatrix)
}
